### ISSUE TITLE
升级到最新版0805后，bypass和dns过滤都无法启动

### ISSUE THREAD

**Issue by jbmmp** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#10]
今天升级到最新版0805后，发现无法上网，dns无法解析，进入路由器管理页面发现，bypass和dns过滤两个服务都无法启动，手动启动也没反应，请问是新版本的原因，或者我这只是个例呢？

**Comment by yangxu52** [comment]
新版加了小猫咪测试中，检查一下

**Comment by yangxu52** [comment]
小猫咪不是很方便，计划取消
