### ISSUE TITLE
passwall可以加入hysteria内核吗

### ISSUE THREAD

**Issue by jbmmp** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#13]
手动安装内核无效，希望可以集成hysterical内核
追求速度的建议使用hysterical
追求安全的可以使用xray+ws+cdn

**Comment by jbmmp** [comment]
自己编译了一个集成hysteria插件的
https://github.com/jbmmp/Phicomm-K2P-K3-OpenWrt-Firmware/releases

**Comment by jbmmp** [comment]
hysteria 和内核有冲突，加入hysteria后vlan没有了，导致不能上网。

**Comment by yangxu52** [comment]
hysteria用的不是基于QUIC协议吗？不支持主流的vmess/vless /trojan吧，那很多机场不能用啊

**Comment by jbmmp** [comment]
现在很多vmess/vless /trojan 全部阻断了，只有用hysteria，还有hysteria速度确实快啊
hysteria主要是udp协议，然后是QUIC协议
我编译的固件，只要集成了hysteria，vlan就没有了，原因不明。

**Comment by yangxu52** [comment]
内核版本的问题
注释掉/PhicommK3/lede/part2.sh 的 20，21，22三行

**Comment by jbmmp** [comment]
多谢，我试试

**Comment by jbmmp** [comment]
注释掉/PhicommK3/lede/part2.sh 的 20，21，22三行后，加入hysteria运行正常
