### ISSUE TITLE
希望增加wol网络唤醒插件

### ISSUE THREAD

**Issue by Boring1998** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#16]
我自己安装老是失败，不是没界面，就是有界面没功能，

**Comment by Boring1998** [comment]
![报错](https://github.com/yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware/assets/55400986/c564cee5-d057-41e0-9e0a-416d16f13aca)
唤醒主机就这样，搞不下去了，希望能自带一个网络唤醒功能

**Comment by yangxu52** [comment]
首先是，不会添加网络唤醒功能。
其次，网络唤醒功能的依赖项还是有好几个的，不是单纯安装就结束了

**Comment by Boring1998** [comment]
那真是太遗憾了，我很需要这个功能，请问下网络唤醒功能的依赖项有哪几个呢
