### ISSUE TITLE
txpower set canceled on K3-lede-2023.04.18-0128?

### ISSUE THREAD

**Issue by cliffmanw** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#18]
root@OP_K3_AP:# iwconfig wlan0 txpower 23
Error for wireless request "Set Tx Power" (8B26) :
    SET failed on device wlan0 ; Not supported.
root@Phicomm-K3:# iwconfig wlan1 txpower 23
Error for wireless request "Set Tx Power" (8B26) :
    SET failed on device wlan1 ; Not supported.

BTW:
这个固件的以太网速度是测试过的K3固件里面最高的。
iperf3 server on K3, test results:
Shortcut-FE 流量分载-开
全锥型 NAT-high perf.
BBR 拥塞控制算法-关
0.00-100.00 sec  9.20 GBytes   790 Mbits/sec
Shortcut-FE 流量分载-开
全锥型 NAT-high perf.
BBR 拥塞控制算法-开
0.00-100.00 sec  8.98 GBytes   771 Mbits/sec
Shortcut-FE 流量分载-关
全锥型 NAT-high perf.
BBR 拥塞控制算法-开
0.00-100.01 sec  9.02 GBytes   775 Mbits/sec

**Comment by yangxu52** [comment]
Maybe, sth. was error in "K3-lede-2023.04.18-0128". It is working in other releases.

BBR may not be fast CCA in TCP, But it is good work for "lower quality networks", It may be good at Gaming.

Where are you from?

**Comment by yangxu52** [comment]
You can try the newest version, Feb 16, 2024.
