### ISSUE TITLE
测试报告

### ISSUE THREAD

**Issue by holoto** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#3]
实测k3 lienol版本 编译出来的固件 程序功能正常 
但是无线驱动有问题 

建议更换为https://github.com/xiangfeidexiaohuo/Phicomm-K3_Wireless-Firmware 
ac88 提取的版本 
ac88_3目前相对稳定

**Comment by yangxu52** [comment]
谢谢，lienol的源码很多是直接同步官方的，时不时会有问题，精力有限慢更
