### ISSUE TITLE
最新版没有去广告了么？

### ISSUE THREAD

**Issue by allforone** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#5]

**Comment by yangxu52** [comment]
因为很玄学，好像生效了，又好像没生效。而且规则更新有问题，暂时移除了。

**Comment by allforone** [comment]
> 因为很玄学，好像生效了，又好像没生效。而且规则更新有问题，暂时移除了。

我这边测试的效果很好

**Comment by yangxu52** [comment]
> > 因为很玄学，好像生效了，又好像没生效。而且规则更新有问题，暂时移除了。
> 
> 我这边测试的效果很好

还在找有没有很简单好用的AD过滤，实在不行还是adbyby+xxrplus算了

**Comment by yangxu52** [comment]
> > 因为很玄学，好像生效了，又好像没生效。而且规则更新有问题，暂时移除了。
> 
> 我这边测试的效果很好

现在改回原来的bypass+dnsfilter了
