### ISSUE TITLE
color os12使用最新版本，连接wifi后会频繁自动掉线问题

### ISSUE THREAD

**Issue by Yep1985** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#6]
![新建 BMP 图像](https://user-images.githubusercontent.com/102252126/159769613-e4b46618-46af-488e-9586-b7ecbc46c790.png)

https://user-images.githubusercontent.com/102252126/159769726-add52581-c7b1-4b8c-a1f1-6407dc927b4e.mp4

**Comment by Yep1985** [comment]
@yangxu52

**Comment by yangxu52** [comment]
我是1+8T也是ColorOS 12 没有任何问题，自己检查一下无线的设置

**Comment by Yep1985** [comment]
> 我是1+8T也是ColorOS 12没有任何问题，自己检查一下无线的设置

😭就很尴尬，还是不行，我恢复路由器出产设置，手机无线也恢复出厂设置了也不行，还是和视频一样，一断一断的 @yangxu52

**Comment by Yep1985** [comment]
> 我是1+8T也是ColorOS 12没有任何问题，自己检查一下无线的设置

😭就很尴尬，还是不行，我恢复路由器出产设置，手机无线也恢复出厂设置了也不行，还是和视频一样，一断一断的。
