### ISSUE TITLE
请问可以添加Haproxy吗？

### ISSUE THREAD

**Issue by ololllolo** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#7]
最近开始用K3，发现那些固件都不行，只有你这个非常的好。干净又整洁。
固件内没有haproxy，所以passwall的负载均衡无法打开。
因为手里有几个不同的节点，如果用haproxy的话，可以有效的解决某些节点失效。

**Comment by yangxu52** [comment]
现在应该已经添加了
