### ISSUE TITLE
无线桥接无法生效

### ISSUE THREAD

**Issue by ImMrMa** [yangxu52/Phicomm-K2P-K3-OpenWrt-Firmware#9]
你好，我考虑把K3的5G天线作为接收和转发：
- 用openwrt单独创建5G  client, 用2.4G 做ap，可以成功。
- 但用5G 做client和AP，就无法成功，openwrt界面没有显示连接主路由成功。

之前用K2P的梅林固件，可以直接用无线桥接功能，用一个5G天线完成client和ap（wifi名也和主路由不一样） 但在K3上好像没有成功过，有什么建议嘛

**Comment by yangxu52** [comment]
具体不知道，K3并没有开源过无线驱动，所以目前K3在openwrt上的无线驱动都是使用的其他同款芯片的路由器的无线驱动，功能可能并不完整
